import { data, type LoaderFunctionArgs } from 'react-router';
import { getInstance } from '~/middleware/i18next';
import type { Route } from './+types/licence';
import ContactButton from '~/components/ContactButton';
import { issuesURL } from '~/data/livedataServer.json';

export async function loader({ context }: LoaderFunctionArgs) {
  let i18n = getInstance(context);
  return data({
    title: i18n.t('common:title'),
  });
}

export function meta({ loaderData }: Route.MetaArgs) {
  const title = 'License & Data Sources' + ' - ' + loaderData.title;
  return [{ title }, { property: 'og:title', content: title }, { property: 'twitter:title', content: title }];
}

const LicencePage = () => {
  return (
    <div className="m-auto max-w-4xl px-4 py-4 sm:py-8 font-pretendard">
      {/* Simple and clean page title */}
      <h1 className="text-3xl md:text-4xl font-bold text-neutral-800 dark:text-white mb-8 border-b border-neutral-300 dark:border-neutral-600 pb-4">License & Data Sources</h1>

      {/* Section: Data Copyright */}
      <section className="mb-10">
        <div className="mt-4 p-4 bg-blue-50 border-l-4 border-blue-500 text-blue-800 dark:bg-blue-900/30 dark:border-blue-400 dark:text-blue-200 rounded-md">
          <h3 className="font-bold text-lg mb-2">Notice</h3>
          <p>
            All copyright of{' '}
            <a href="https://bluearchive.jp/" target="_blank" rel="noopener noreferrer">
              <b className="hover:underline">"Blue Archive"</b>
            </a>{' '}
            belongs to{' '}
            <a href="https://www.nexon.com" target="_blank" rel="noopener noreferrer">
              <b className="hover:underline">NEXON Korea Corp.</b>
            </a>
            ,{' '}
            <a href="https://www.nexongames.co.kr/" target="_blank" rel="noopener noreferrer">
              <b className="hover:underline">NEXON GAMES Co., Ltd.</b>
            </a>
            , and{' '}
            <a href="https://www.yo-star.com" target="_blank" rel="noopener noreferrer">
              <b className="hover:underline">YOSTAR, Inc.</b>
            </a>
          </p>
        </div>
      </section>
      <section className="mb-10">
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Data</h2>
      </section>

      {/* Section: Icons & Images */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Icons & Images</h2>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 mt-4 pl-2">
          <li>
            <b>Site logo, Star level icon:</b> Written by myself referring to the game asset
          </li>
          <li>
            <b>Student Portraits, In-Game Item Icons:</b>{' '}
            <a href="https://schaledb.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Schale DB
            </a>
          </li>
          <li>
            <b>Teran Icon:</b> Traced game assets by myself
          </li>
          <li>
            <b>Others:</b>{' '}
            <a href="https://https://github.com/react-icons/react-icons/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              React Icons
            </a>{' '}
            or Generated by LLM
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Data Sources</h2>

        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Total Assault Overall</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            <b>S43-S76:</b>{' '}
            <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Someone's Google Storage API
            </a>
          </li>
          <li>
            <b>S77-S80:</b>{' '}
            <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Plana Stats
            </a>
          </li>
          <li>
            <b>S81:</b> Provided by an anonymous data contributor
          </li>
          <li>
            <b>S82:</b>{' '}
            <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Plana Stats
            </a>
          </li>
          <li>
            <b>S83-Current:</b> Provided by an anonymous data contributor
          </li>
        </ul>
        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Total Assault Teams</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            <b>S43-S46:</b>{' '}
            <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Someone's Google Storage API
            </a>
          </li>
          <li>
            <b>S47-S79:</b>{' '}
            <a href="https://arona.ai/raidreport" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Arona.AI Total Assault Report (no longer accessible)
            </a>
          </li>
          <li>
            <b>S80-Current:</b>{' '}
            <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Plana Stats
            </a>
          </li>
        </ul>
        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Grand Assault Overall</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            <b>S1-S21:</b>{' '}
            <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Someone's Google Storage API
            </a>
          </li>
          <li>
            <b>S22-S25:</b>{' '}
            <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Plana Stats
            </a>
          </li>
          <li>
            <b>S26-Current:</b> Provided by an anonymous data contributor
          </li>
        </ul>
        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Grand Assault Teams</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            <b>S1-S23:</b>{' '}
            <a href="https://arona.ai/eraidreport" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Arona.AI Grand Assault Report (no longer accessible)
            </a>
          </li>

          <li>
            <b>S24-Current:</b>{' '}
            <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Plana Stats
            </a>
          </li>
        </ul>

        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Assault Live Data</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>Provided by an anonymous data contributor</li>
        </ul>

        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Korea Server Assault Data</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            Total Assault & Grand Assault Distribution Google Spreadsheets: <br />
            <a href="https://docs.google.com/spreadsheets/d/1JGBeDCu8KtVIsWd4QbQhNJekeG1YD8ZmGmbfXYznT7k" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline break-all">
              docs.google.com/spreadsheets/...
            </a>
          </li>
          <li>
            Someone's Google Storage API: <br />
            <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline break-all">
              storage.googleapis.com/info.herdatasam.me
            </a>
          </li>
        </ul>

        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Student Matadata</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            Student ID, Bullet Type, Alias, Position, Squad Type, Tactic Role, Academy:
            <br />
            <a href="https://schaledb.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Schale DB
            </a>
          </li>
          <li>
            Experience Tables:
            <br />
            <a href="https://bluearchive.wiki/wiki/Experience_tables/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Blue Archive Wiki
            </a>
          </li>
        </ul>

        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Jukebox Data</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            Base Data:
            <br />
            <a href="https://arona.ai/jukebox/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Arona.AI BGM Player (no longer accessible)
            </a>
          </li>
          <li>
            Title & Composer:
            <br />
            <a href="https://bluearchive.wiki/wiki/Music" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Blue Archive Wiki
            </a>
          </li>
          <li>
            Music Video:
            <br />
            <a href="https://www.youtube.com/@mo2bluearchive/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              MO2 Youtube Channel
            </a>
          </li>
        </ul>
        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Event Data</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            Base Data & Translation:
            <br />
            <a href="https://schaledb.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Schale DB
            </a>
          </li>
        </ul>

        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            Pyroxene Data
            <br />
            <a
              href="https://docs.google.com/spreadsheets/d/1_Zjt_OM9XXidY3uYYDK92W9GrR3DN5cQsZ0IJsoEbjY/edit#gid=1082031226/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-500 hover:underline"
            >
              Pyroxene Memo Planner 2.09 (Google Spreadsheets)
            </a>
          </li>
        </ul>

        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Video Analysis (BETA) Data</h3>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>Student identification data derived from YouTube video thumbnails and descriptions.</li>
          <li>Thumbnails were analyzed using image similarity matching (NCC) and object detection (YOLO v26 nano).</li>
          <li>Video descriptions were analyzed using a locally-run AI language model (Gemma 4 E4B).</li>
        </ul>
      </section>

      {/* Section: References */}
      <section>
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">References During Development</h2>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 mt-4 pl-2">
          <li>
            <a href="https://bluearchive-torment.netlify.app/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              BA Torment
            </a>
          </li>
          <li>
            <a href="https://hina.loves.midokuni.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Hina Loves Midokuni
            </a>
          </li>
          <li>
            <a href="https://www.souriki-border.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              そうりきボーダー
            </a>
          </li>
          <li>
            <a href="https://mollulog.net/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              몰루로그 - 블루 아카이브 미래시/통계 정보 모음
            </a>
          </li>
          <li>
            <a href="https://kina-ko-m-ochi.net/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              ブルアカの攻略・ファンツールまとめ｜きなこもち
            </a>
          </li>
          <li>
            <a href="https://justin163.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Blue Archive Resource Planner (Justin163)
            </a>
          </li>
          <li>and various source codes found on GitHub.</li>
        </ul>
      </section>

      {/* Section: License */}
      <section className="mt-10 mb-10">
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Source Code License</h2>
        <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-4 mb-2">This Website</h3>
        <ul className="list-disc list-inside space-y-1 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>Distributed under the MIT License.</li>
          <li>
            Source Code:{' '}
            <a href="https://github.com/bluekiseki/BA-mobilization-trends-public" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Github
            </a>
          </li>
          <li>For dependency licenses, please refer to the `package.json` in the source code.</li>
        </ul>
      </section>

      {/* Section: Data Collection Tools */}
      <section className="mt-10 mb-10">
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">3rd Party Data Collection</h2>
        <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 mt-4 pl-2">
          {/* <li>
              <a href="https://vercel.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
                Vercel
              </a>
              : Server Hosting.
            </li> */}
          <li>
            <a href="https://pages.cloudflare.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Cloudflare Pages
            </a>
            : Server Hosting.
          </li>
          {/* <li><a href="https://github.com/vercel/analytics" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Vercel Analytics</a>: Tracks site performance.</li> */}
          <li>
            <a href="https://www.cloudflare.com/insights/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Cloudflare Insights
            </a>
            : Tracks site performance.
          </li>
          <li>
            <a href="https://www.cloudflare.com/developer-platform/products/r2/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Cloudflare R2
            </a>
            : Used for asset storage.
          </li>
          <li>
            <a href="https://posthog.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              PostHog
            </a>
            : Provides user analytics and tracking. Cookies are disabled.
          </li>
        </ul>

        {/* Data Usage Notice - Updated */}
        <div className="mt-6 p-4 bg-neutral-100 dark:bg-neutral-800/50 rounded-lg border border-neutral-200 dark:border-neutral-700 text-sm">
          <p className="font-semibold text-neutral-800 dark:text-neutral-200 mb-2">Data Collection Details</p>
          <p className="text-neutral-600 dark:text-neutral-400 mb-3">These third-party services may collect standard technical data commonly used in web analytics, including but not limited to:</p>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-1 mb-4 text-neutral-600 dark:text-neutral-400 list-disc list-inside pl-2 font-mono text-xs">
            <li>IP Address</li>
            <li>User-Agent</li>
            <li>Timezone</li>
            <li>Screen Size</li>
            <li>Session Duration</li>
            <li>Referring Domain</li>
          </ul>
          <p className="text-neutral-600 dark:text-neutral-400">
            This data is utilized strictly for operational purposes, such as debugging, site stability, security defense (e.g., preventing malicious attacks), and analyzing demographic trends to
            assist with future service direction.
          </p>
        </div>
      </section>

      <section className="mt-10 mb-10">
        <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Bug Reports, Translation & Contact</h2>
        <ul className="list-disc list-inside space-y-1 text-neutral-600 dark:text-neutral-400 pl-2">
          <li>
            For bug reports or translation contributions, please visit{' '}
            <a href={issuesURL} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
              Github issues
            </a>
          </li>
          <li>
            or{' '}
            <a className="text-blue-500 hover:underline">
              <ContactButton>Email</ContactButton>
            </a>
          </li>
        </ul>
      </section>
    </div>
  );
};

export default LicencePage;
